checks:
  - use: version
    run: node -v
    version:
      min: '14'
    name: node
    messages:
     - 'NodeJs'
     - 'of Nodejs'
  - use: docker
    version:
      min: '20.10.1'
  - use: docker-compose
    version:
      min: '1.29.2'
      max: '2.0.0'
  - use: npm_auth
  - use: available_port
    port: 80
    name: nginx
    messages:
     - 'Nginx'
     - ''
